name: Skaffold Workflow
on: push
jobs:
  skaffold:
    name: Run Skaffold CI
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Start Minikube
        id: minikube
        uses: hiberbee/github-action-minikube@latest
        with:
          profile: github

      - name: Setup Helm
        uses: hiberbee/github-action-helm@latest

      - name: Install Helm Repos
        uses: hiberbee/github-action-helm@latest
        with:
          helm: repo list
          repository-config: ./helm-repos.yml

      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x skaffold
          sudo install skaffold /usr/local/bin/

      - name: Skaffold Build
        run: skaffold build --file-output build.json

      - name: Skaffold Test
        run: skaffold test --build-artifacts build.json
